import React, { useEffect, useMemo, useState } from 'react';
import toast from 'react-hot-toast';
import api, { normalizePaginatedResponse } from '../../services/api';
import { getProducts, StoreProduct } from '../../services/storesApi';
import { Button, Card } from '../../components/ui';

interface Ingredient { id:string; display_name:string }
interface Row { ingredient:string; quantity_g:string }
interface Recipe { id:string; serving_size_g:string; household_measure:string; status:string; items:Row[]; calculation?: { per_100g:Record<string,string|null>; missing_nutrients:string[] } }

export default function RecipeBuilder({storeSlug,ingredients}:{storeSlug?:string;ingredients:Ingredient[]}) {
  const [products,setProducts]=useState<StoreProduct[]>([]); const [product,setProduct]=useState('');
  const [recipe,setRecipe]=useState<Recipe|null>(null); const [rows,setRows]=useState<Row[]>([]);
  const [serving,setServing]=useState('100'); const [measure,setMeasure]=useState('1 unidade'); const [saving,setSaving]=useState(false);
  useEffect(()=>{if(!storeSlug)return;getProducts({store:storeSlug,status:'active',page_size:500}).then(r=>setProducts(r.results)).catch(()=>toast.error('Erro ao carregar pratos'));},[storeSlug]);
  useEffect(()=>{if(!product){setRecipe(null);setRows([]);return;}api.get('/nutrition/recipes/',{params:{product,page_size:1}}).then(r=>{const found=normalizePaginatedResponse<Recipe>(r.data)[0]||null;setRecipe(found);setRows(found?.items||[]);setServing(found?.serving_size_g||'100');setMeasure(found?.household_measure||'1 unidade');}).catch(()=>toast.error('Erro ao carregar receita'));},[product]);
  const available=useMemo(()=>ingredients.filter(i=>!rows.some(r=>r.ingredient===i.id)),[ingredients,rows]);
  const save=async()=>{if(!product||rows.length===0)return toast.error('Escolha o prato e adicione ingredientes');setSaving(true);const payload={product,serving_size_g:serving,household_measure:measure,status:'estimated',calculation_mode:'calculated',items:rows.map((r,i)=>({...r,sort_order:i}))};try{const response=recipe?await api.patch(`/nutrition/recipes/${recipe.id}/`,payload):await api.post('/nutrition/recipes/',payload);setRecipe(response.data);toast.success('Receita calculada e perfil nutricional atualizado');}catch{toast.error('Não foi possível salvar a receita');}finally{setSaving(false)}};
  return <Card className="p-5 space-y-4"><div><h2 className="text-lg font-semibold">Receita do prato</h2><p className="text-sm opacity-65">Reaproveita o produto existente; aqui você informa apenas os ingredientes e seus pesos.</p></div><div className="grid md:grid-cols-3 gap-3"><label className="text-sm md:col-span-1">Produto<select className="mt-1 w-full rounded border p-2 bg-transparent" value={product} onChange={e=>setProduct(e.target.value)}><option value="">Selecione…</option>{products.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label className="text-sm">Porção (g)<input type="number" min="1" className="mt-1 w-full rounded border p-2 bg-transparent" value={serving} onChange={e=>setServing(e.target.value)}/></label><label className="text-sm">Medida caseira<input className="mt-1 w-full rounded border p-2 bg-transparent" value={measure} onChange={e=>setMeasure(e.target.value)}/></label></div>{product&&<><div className="space-y-2">{rows.map((row,index)=><div key={`${row.ingredient}-${index}`} className="grid grid-cols-[1fr,120px,auto] gap-2"><select className="rounded border p-2 bg-transparent" value={row.ingredient} onChange={e=>setRows(rows.map((r,i)=>i===index?{...r,ingredient:e.target.value}:r))}>{ingredients.map(i=><option key={i.id} value={i.id}>{i.display_name}</option>)}</select><input aria-label="Quantidade em gramas" type="number" min="0.001" step="0.1" className="rounded border p-2 bg-transparent" value={row.quantity_g} onChange={e=>setRows(rows.map((r,i)=>i===index?{...r,quantity_g:e.target.value}:r))}/><button className="px-3 text-red-600" onClick={()=>setRows(rows.filter((_,i)=>i!==index))}>Remover</button></div>)}</div><div className="flex flex-wrap gap-2"><Button variant="secondary" disabled={!available.length} onClick={()=>setRows([...rows,{ingredient:available[0]?.id||'',quantity_g:'100'}])}>Adicionar ingrediente</Button><Button disabled={saving||!rows.length} onClick={save}>{saving?'Calculando…':'Salvar e calcular'}</Button></div>{recipe?.calculation&&<div className="rounded-lg border border-black/10 p-3"><p className="font-semibold text-sm">Resumo por 100 g</p><div className="mt-2 grid grid-cols-2 md:grid-cols-5 gap-2 text-xs">{Object.entries(recipe.calculation.per_100g).map(([k,v])=><div key={k}><span className="opacity-60">{k.replace(/_/g,' ')}</span><strong className="block">{v??'—'}</strong></div>)}</div>{recipe.calculation.missing_nutrients.length>0&&<p className="mt-2 text-xs text-amber-700">Pendentes para impressão oficial: {recipe.calculation.missing_nutrients.join(', ')}</p>}</div>}</>}</Card>;
}
