export { Button } from './Button';
export type { ButtonProps, ButtonVariant } from './Button';
export { Card } from './Card';
export type { CardProps } from './Card';
export { StatCard } from './StatCard';
export type { StatCardProps, StatCardTone } from './StatCard';
export { Input, SearchInput } from './input';
export { Label } from './label';
export { Modal, ConfirmModal, ModalHeader, ModalBody, ModalFooter } from './modal';
export type { ModalProps, ModalHeaderProps, ConfirmModalProps } from './modal';
export { Badge } from './Badge';
export type { BadgeProps, BadgeTone } from './Badge';
export { Skeleton, TableSkeleton, CardSkeleton, StatsSkeleton } from './skeleton';
export { Dropdown, DropdownButton } from './dropdown';
export { Toast, ToastContainer } from './toast';
export { PeriodChips, PERIODOS_PADRAO } from './PeriodChips';
export type { PeriodChipsProps, PeriodOption } from './PeriodChips';

// Chassi de página — o cabeçalho, os indicadores, os insights e o vazio de
// TODA tela do painel vivem aqui. Não monte esses blocos à mão numa página.
export { PageShell } from './PageShell';
export type { PageShellProps, TrilhaItem } from './PageShell';
export { KpiGrid } from './KpiGrid';
export type { KpiGridProps, KpiItem } from './KpiGrid';
export { InsightList } from './InsightList';
export type { InsightListProps, InsightItem, InsightDirecao } from './InsightList';
export { EmptyState } from './EmptyState';
export type { EmptyStateProps, EmptyStateBeneficio } from './EmptyState';
export { PhonePreview } from './PhonePreview';
export type { PhonePreviewProps } from './PhonePreview';
export { RowActions, linhaClicavel } from './RowActions';
export type { RowActionsProps, RowAction } from './RowActions';
export { PageTabs } from './PageTabs';
export type { PageTabsProps, PageTab } from './PageTabs';
export { FormChecklist } from './FormChecklist';
export type { FormChecklistProps, ItemDeChecklist } from './FormChecklist';
export { ChoiceCards } from './ChoiceCards';
export type { ChoiceCardsProps, OpcaoDeEscolha } from './ChoiceCards';
export { FormSummary } from './FormSummary';
export type { FormSummaryProps, LinhaDeResumo } from './FormSummary';
